<?php

namespace Belectrika\GridBundle\Entity\Price\Item;

use Doctrine\ORM\EntityRepository;

/**
 * ChangelogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangelogRepository extends EntityRepository
{
    /**
     * Get changelogs qb for the last $period seconds
     *
     * @param string $pageId An id (unique hash) of page that requests for changes
     * @param int $period A period of time in seconds
     */
    public function getLatestForPage($pageId, $period = 10)
    {
        return $this->createQueryBuilder('l')
            ->leftJoin('l.item', 'i')
            ->where('l.created > ?1')
            ->andWhere('l.pageId != ?2')
            ->orderBy('l.created')
            ->setParameter('1', new \DateTime(sprintf('%s seconds ago', $period)))
            ->setParameter('2', $pageId)
            ->getQuery()
            ->getResult();
    }
}