<?php

namespace Belectrika\GridBundle\Entity\Price\Item;

use Doctrine\ORM\EntityRepository;

/**
 * ChangelogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangelogRepository extends EntityRepository
{
}