<?php

namespace Belectrika\GridBundle\Entity\Price\Item;

use Doctrine\ORM\EntityRepository;

/**
 * ChangelogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangelogRepository extends EntityRepository
{
    /**
     * Get changelogs qb for the last $period seconds
     *
     * @param int $period
     */
    public function getLatestQ($period = 10)
    {
        return $this->createQueryBuilder('l')
            ->leftJoin('l.item', 'i')
            ->where('l.created > ?1')
            ->orderBy('l.created')
            ->setParameter('1', new \DateTime(sprintf('%s seconds ago', $period)));
    }
}