<?php

namespace Belectrika\GridBundle\Entity\Price;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getForGroup($groupId)
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i')
            ->innerJoin('i.group', 'g')
            ->where('g.id = ?1')
            ->setParameter('1', $groupId);

        return $qb->getQuery()->getResult();
    }
}